<font size="2" color="#191970">You Just Requested The Following Drug Name:&nbsp;<font size="3" color=red><b><u><?php echo $drug; ?></u></b></font></font>
<h4>A to Z Drug Facts from <font color="#006400">SkolarMD</font></h4>

<HR NOSHADE>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=dosage">What is the Route/Dosage?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=indications">What are the Indications?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=contraindications">What are the Contraindications?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=adversereactions">What are the Adverse Reactions?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=actions">How does it Work(Pharmakology/Kinetics)?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=interactions">What are its Drug Interactions?</a><br>
<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=labtestinterferences">How can it Interfere with Lab Tests?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=precautions">What are the Precautions?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&query=<?php echo $drug;?>&resource=atoz&caption=patientcare">What Additional Patient Care considerations are there<br>(Sign of Overdosage, Assessment/Interventions, Patient Information)?</a>

<HR NOSHADE>
<h4>Other Resources from <font color="#006400">SkolarMD:</font></h4>
<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&resource=CLINEGUIDE">What does Clin-eguide say about this Drug?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&resource=fdawatch">What does FDA Alerts say about this Drug?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&resource=fivemcc">What does Griffith's 5 Minutes Clinical Consult say About This Drug?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&resource=harrison">What does Harrison's Principles of Internal Medicine?</a>

<HR NOSHADE>
<h4>Category Listings from <font color="#006400">SkolarMD:</font></h4>
<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&category=TEXTBOOK">What TextBooks are Available?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&category=DRUGDB">What Other Information about this Drug?</a><br>

<a target=_blak href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&category=ALLGUIDELINES">What Other Evidence-based Medicine and Guidelines are out there?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&category=FULLTEXT">What does MEDLINE article database say about this Drug?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&category=PTEDU">What Patient Education Materials are there?</a><br>

<a target=_blank href="http://md.skolar.com/gateway?affilid=omhcolumbia&uid=omhcolumbia&query=<?php echo $drug;?>&category=SPCL_CNT">What Other Web Content for this Drug?</a>
